/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface": "#fff9f0",
        "on-primary-fixed": "#221b00",
        "tertiary-fixed-dim": "#ffb3b0",
        "surface-container-highest": "#e7e2d9",
        "inverse-surface": "#32302a",
        "secondary-fixed": "#96f89f",
        "on-background": "#1d1b16",
        "on-tertiary-fixed-variant": "#8c1520",
        "tertiary-container": "#ffd1ce",
        "on-surface": "#1d1b16",
        "on-tertiary-container": "#b03136",
        "on-tertiary-fixed": "#410006",
        "on-secondary-fixed": "#002107",
        "on-error-container": "#93000a",
        "secondary": "#006e29",
        "surface-dim": "#dfd9d1",
        "inverse-on-surface": "#f6f0e7",
        "primary-fixed-dim": "#e8c426",
        "outline": "#7e7761",
        "outline-variant": "#d0c6ad",
        "surface-tint": "#705d00",
        "primary-fixed": "#ffe173",
        "primary-container": "#ffd93d",
        "on-surface-variant": "#4d4633",
        "surface-variant": "#e7e2d9",
        "on-primary-fixed-variant": "#554500",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#00531d",
        "surface-bright": "#fff9f0",
        "tertiary-fixed": "#ffdad8",
        "secondary-container": "#93f59c",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ede7df",
        "secondary-fixed-dim": "#7bdb85",
        "inverse-primary": "#e8c426",
        "surface-container": "#f3ede4",
        "on-primary": "#ffffff",
        "tertiary": "#ae2f34",
        "primary": "#705d00",
        "on-secondary": "#ffffff",
        "background": "#fff9f0",
        "on-secondary-container": "#00732b",
        "on-error": "#ffffff",
        "on-primary-container": "#725e00",
        "surface-container-low": "#f9f3ea"
      },
      fontFamily: {
        "headline": ["Chewy", "system-ui"],
        "body": ["Chewy", "system-ui"],
        "label": ["Chewy", "system-ui"],
        "chewy": ["Chewy", "system-ui"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
